hra-download-state behavioral
hubmapconsortium/hra-ui pull request #112
Opened 2023-03-03 22:44 UTC by sanket1211996

2023-03-16 21:02 UTC, axdanbol requested changes

2023-03-16 21:02 UTC, axdanbol commented on libs/state/src/lib/download-file/download-file.state.ts
> +
If url is available then download directly. Otherwise if format is supported convert

2023-03-24 22:29 UTC, sanket1211996 commented
@bherr2  @axdanbol Code is ready for review there is some issue with checks. Could you please check.

2023-03-27 21:52 UTC, axdanbol requested changes

2023-03-27 21:52 UTC, axdanbol commented on libs/state/src/lib/download/download.model.ts
> +export type DownloadModel = DownloadFormat[];
Add doc comment

2023-03-27 21:52 UTC, axdanbol commented on libs/state/src/lib/download/index.ts
> +export { FileFormat, DownloadFormat } from './download.model';
Export selectors

2023-03-27 21:52 UTC, axdanbol commented on libs/state/src/lib/download/download.state.ts
> +  blobDownload(blob: Blob, fileName: string) {
Rename to `downloadData`
Should also be private

2023-03-27 21:52 UTC, axdanbol commented on libs/state/src/lib/download/download.state.ts
> +  inferFileExtension(fileUrl: string) {
Don't need to guess extension. You get that from the format

2023-03-27 21:52 UTC, axdanbol commented on libs/state/src/lib/download/download.state.ts
> +  async downloadAndSave(fileUrl: string, fileName: string) {
Rename to `downloadRemoteData`

2023-03-27 21:52 UTC, axdanbol commented on libs/state/src/lib/download/download.state.ts
> +  inferFilename(fileUrl: string) {
Rename to `guessFilename`
Also it doesn't work as intended. Try the following examples:
`abc`
`abc/def`
`abc/def/`

2023-03-27 21:52 UTC, axdanbol commented on libs/state/src/lib/download/download.state.ts
> +    ctx?.drawImage(image, 0, 0);
Should fail if we can't draw it (i.e. no context)

2023-03-27 21:52 UTC, axdanbol commented on libs/state/src/lib/download/download.state.ts
> +  async createCanvas(image: HTMLImageElement): Promise<HTMLCanvasElement> {
Rename to `convertImageToCanvas`

2023-04-03 17:26 UTC, axdanbol requested changes

2023-04-03 17:26 UTC, axdanbol commented on libs/state/src/lib/download/download.action.ts
> +export class ClearEntry extends Action('Clear') {
I rather have an action that clears all entries (i.e. sets entries to the empty object {}) than having to clear each one by one

2023-04-03 17:26 UTC, axdanbol commented on libs/state/src/lib/download/download.selectors.ts
> +   * @param state
Add docs to param and return tags

2023-04-03 17:26 UTC, axdanbol commented on libs/state/src/lib/download/download.state.ts
> +  private readonly http = inject(HttpClient);
Code doc

2023-04-03 17:26 UTC, axdanbol commented on libs/state/src/lib/download/download.state.ts
> +        this.downloadData(new Blob([entry.data]), filename);
Use guessFilename with an empty url '' for the filename here

2023-04-05 20:04 UTC, axdanbol approved these changes

2023-04-05 20:09 UTC, merged