update tooltip text for anchor and cell types
hubmapconsortium/hra-ui pull request #501
Opened 2024-06-27 13:57 UTC by bhushankhope

2024-06-28 15:46 UTC, LibbyUX submitted a review, later dismissed

2024-07-01 17:04 UTC, axdanbol requested changes
Two small tweaks

2024-07-01 17:04 UTC, axdanbol commented on libs/cde-visualization/src/lib/components/cell-types/cell-types.component.scss
> +            border-top-left-radius: 8px;
Use rem instead of px

2024-07-01 17:04 UTC, axdanbol commented on libs/cde-visualization/src/lib/components/visualization-header/visualization-header.component.html
> +    <a
Missing `rel="noopener noreferrer"`

2024-07-01 17:19 UTC, axdanbol approved these changes

2024-07-01 17:23 UTC, merged