show/hide empty fields and css updates on vis page
hubmapconsortium/hra-ui pull request #518
Opened 2024-07-02 16:03 UTC by bhushankhope

- add show/hide empty fields functionality
- update css of color picker rows
- update css of download png button

2024-07-03 17:59 UTC, LibbyUX requested changes
Hi @bhushankhope - This is looking pretty good.

**Approved:**
- update css of color picker rows
- update css of download png button

Show/hide functionality looks good for sample visualizations.

I am requesting changes for user generated **add show/hide empty fields functionality**
- I created my own visualization and technology still showed
  - Note that I did add something to the input initially, however, I backspaced it out. The result was that it showed in the metadata.
- I am also hoping we can get this closer to specification for user-generated with the colors:

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/041e7975-c5de-4d8e-a353-af3fee73327b)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/1ed4459b-5818-48a7-bee8-e0b8e1455d39)

2024-07-03 18:37 UTC, axdanbol requested changes
Don't forget to add code docs!

2024-07-03 18:37 UTC, axdanbol commented on libs/cde-visualization/src/lib/models/metadata.ts
> +  fileUrl: string;
Let's rename this to `sampleUrl` to prevent confusion

2024-07-05 14:07 UTC, axdanbol approved these changes

2024-07-05 14:08 UTC, merged