Update source metadata and enable links to paper
hubmapconsortium/hra-ui pull request #536
Opened 2024-07-09 20:48 UTC by edlu77

Closes #513

2024-07-09 21:11 UTC, LibbyUX requested changes
This source data section is looking amazing, @edlu77 ! I am loving the updated collapse functionality. I am also loving the logic of seeing one row if there's only one data source. Exquisite!

A couple of hopefully quick CSS requests:
- Initially, when I designed the new source data area, the paper title was supposed to link out elsewhere, but it appears this may have changed due to the data we have available. These paper titles may need to use our [table text button](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=2319-4362&t=ZvRBz2QZBMH9Rdv7-4) component in future versions. For now, can you please use our HRA blue (it appears black) for plain text in the table here instead?
- Question: Is the DOI link button using the 500 weight from our [table text button](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=2319-4362&t=ZvRBz2QZBMH9Rdv7-4)? It appears a little thicker currently.

![525EE666-8120-4AC9-ADDA-4F601110D349](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e8ff47a1-04c9-43f7-b0a7-8bbed012aed6)


![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/759db33e-3d3f-445e-a371-23a28d2fffa8)

2024-07-10 13:06 UTC, LibbyUX approved these changes
Beautiful! Thank you @edlu77

2024-07-10 15:34 UTC, axdanbol requested changes

2024-07-10 15:34 UTC, axdanbol commented on libs/components/molecules/src/lib/source-list/source-list.component.html
> +          [href]="sourceLink"
Replace with `[href]="row.link"`

2024-07-10 15:34 UTC, axdanbol commented on libs/components/molecules/src/lib/source-list/source-list.component.ts
> +  sourceLink = '';
Remove

2024-07-10 15:34 UTC, axdanbol commented on libs/components/molecules/src/lib/source-list/source-list.component.ts
> +    this.sourceLink = item.link;
Remove

2024-07-10 15:49 UTC, axdanbol approved these changes

2024-07-10 15:50 UTC, merged