Cde create vis updates
hubmapconsortium/hra-ui pull request #572
Opened 2024-07-22 15:55 UTC by edlu77

#556

2024-07-22 16:16 UTC, LibbyUX requested changes
Hi, @edlu77! Our create vis app is looking amazing! Thank you so much for working on this!

My feedback/questions:
- The background is looking fresh!
- The Upload CSV button appears different visually. The top one is up to spec. Can we use that same button in the Upload Color Map component?
- `Action Required: Upload Color Map`: This heading appears thinner than our Metropolis 500 around the rest of the app. I inspected and it looks like this instance could be 400.
- The responsiveness of this page is excellent.

![image](https://github.com/user-attachments/assets/c6d620b1-66c2-4e1e-915d-bc7f57e5fcc5)

![image](https://github.com/user-attachments/assets/3c8c0d13-a2e7-4a20-abb8-153cc0c60383)

2024-07-22 20:32 UTC, edlu77 commented
@LibbyUX Updates are in! Let me know if you spot anything else.

2024-07-22 20:34 UTC, LibbyUX approved these changes
It's fabulous @edlu77! Thanks for knocking this out!

2024-07-22 22:10 UTC, axdanbol requested changes

2024-07-22 22:10 UTC, axdanbol commented on apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.theme.scss
> +$blue-palette: map.get(palettes.$palettes, 'blue');
This should come from the `$theme` variable. Use `mat.get-theme-color($theme, accent, lighter)` to get blue 500

2024-07-22 22:10 UTC, axdanbol commented on apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.theme.scss
> +    --mat-option-selected-state-layer-color: #{mat.get-theme-color($theme, accent, 500)};
Use `lighter` instead of 500

2024-07-22 22:10 UTC, axdanbol commented on apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.theme.scss
> +    --mat-option-selected-state-label-text-color: #{mat.get-theme-color($theme, accent, 900)};
Use `darker` instead of 900

2024-07-22 22:10 UTC, axdanbol commented on apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.ts
> +  get nodesErrorInstructions(): string {
Major duplication between the two getters. Refactor to a private helper function:
```ts
private getErrorActionMessage(error: ExtendedFileLoadError | undefined, fileDescription: string): string {
  switch (error?.type) {
    case undefined:
      return '';
    case 'type-error':
      return `Please upload a ${fileDescription} table CSV file.`;
    default:
      return 'Please upload a CSV file with the required columns.';
}

get nodesErrorActionMessage(): string {
  return this.getErrorActionMessage(this.nodesLoadError, 'cell type table')
}
```

2024-07-24 15:00 UTC, axdanbol commented on apps/cde-ui/src/app/components/file-upload/file-upload.component.html
> +<h3 class="subtitle">
Change class to `action-required`

2024-07-24 15:02 UTC, axdanbol commented on apps/cde-ui/src/app/components/file-upload/file-upload.component.html
> +  <mat-icon svgIcon="settings_alert"></mat-icon>
Use the material icon, i.e. `<mat-icon class="alert">settings_alert</mat-icon>`

2024-07-24 15:03 UTC, axdanbol commented on apps/cde-ui/src/app/components/file-upload/file-upload.component.html
> +  <div class="upload-errors" [class.show]="errorMessage()">
Update class name to `error` and remove `[class.show]=...`

2024-07-24 15:04 UTC, axdanbol commented on apps/cde-ui/src/app/components/file-upload/file-upload.component.html
> +    <span class="error-message">{{ errorMessage() }}</span>
Update class to `message` and refer to it in scss like this:
```scss
.error {
  ...
  .message {
    ...
  }
}

or

.error .message {
  ...
}
```

2024-07-24 15:04 UTC, axdanbol commented on apps/cde-ui/src/app/components/file-upload/file-upload.component.html
> +    <span class="error-instructions">{{ errorActionMessage() }}</span>
Update class to `action`

2024-07-24 15:21 UTC, axdanbol commented on apps/cde-ui/src/app/components/file-upload/file-upload.component.html
> +@if (file) {
Update this to `file && !errorMessage()` to hide when there are errors

2024-07-25 15:16 UTC, axdanbol requested changes

2024-07-25 15:16 UTC, axdanbol commented on apps/cde-ui/src/app/components/file-upload/file-upload.component.html
> +  [class.layout-a]="layout() === 'layout-a'"
Work with @LibbyUX  to remove inconsistent layouts between csv and color map upload areas

2024-07-25 15:16 UTC, axdanbol commented on apps/cde-ui/src/app/components/file-upload/file-upload.component.ts
> +  readonly uploaded = input<boolean>();
This input is not necessary. You already have this information from a combination of the values of `file` and `errorMessage`

2024-07-25 15:16 UTC, axdanbol commented on apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.theme.scss
> +$blue-palette: map.get(palettes.$palettes, 'blue');
Remove this line

2024-07-26 15:07 UTC, axdanbol approved these changes

2024-07-26 15:07 UTC, merged