Design system brandmark storybook
hubmapconsortium/hra-ui pull request #594
Opened 2024-07-30 17:31 UTC by edlu77

#583

2024-07-30 18:13 UTC, LibbyUX reviewed
This looks great!

Should I be reviewing if the component in Storybook is linked to the [Brandmark Figma canvas](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=82-776)? We will need to add it if so!

Mentioning @axdanbol for help answering this review workflow question, too!

Thanks so much!

![image](https://github.com/user-attachments/assets/72fae9d3-832f-42e3-8d23-6b3f8d941c89)

2024-07-30 18:15 UTC, edlu77 commented
@LibbyUX Thanks for catching that! I forgot to add in the link. WIll do that now.

2024-08-01 17:56 UTC, axdanbol requested changes
Please create a single svg that uses `currentColor` to control the color instead of multiple images

2024-08-01 17:56 UTC, axdanbol commented on libs/design-system/brandmark/src/lib/brandmark.component.html
> +<img class="hra-brandmark" [attr.src]="svgPath() | assetUrl" alt="Human Reference Atlas brandmark" />
Use the `inlineSvg` directive from `ng-inline-svg-2` (already installed) to load the svg

2024-08-01 17:56 UTC, axdanbol commented on libs/design-system/brandmark/src/lib/brandmark.component.scss
> +  display: block;
Add a css variable to control the color, `--hra-brandmark-color`. Default to `--sys-tertiary`

2024-08-01 17:56 UTC, axdanbol commented on libs/design-system/brandmark/src/lib/brandmark.component.ts
> +  readonly color = input<string>('default');
Color will be controlled from css so please remove this input

2024-08-01 17:56 UTC, axdanbol commented on libs/design-system/brandmark/src/lib/brandmark.component.ts
> +  readonly small = input<boolean>(false);
Since the brandmark is an svg it should automatically scale to whatever size we need so this input is not needed.

2024-08-05 18:22 UTC, axdanbol approved these changes

2024-08-05 18:22 UTC, merged