Design system storybook mat sort header
hubmapconsortium/hra-ui pull request #614
Opened 2024-08-07 00:57 UTC by edlu77

#574

Sort arrow is not actually using a mat-icon since it's actually an elaborate series of divs and is pretty hard to change. I tried to make it as close to spec as possible though.

2024-08-08 16:36 UTC, LibbyUX requested changes
Thanks so much for getting this started, @edlu77 ! It's looking really good!

A request on this: Can we make the underline only appear on keyboard tab Focus state? Note that this is different from our focus visible state. Please see all state variants in the [Design System Repo](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=2015-4422&m=dev). The state behavior that Angular provides in their [table with sorting example](https://material.angular.io/components/sort/overview#table-sorting) is exactly what I'm looking for!

<img width="1090" alt="Screenshot 2024-08-08 at 12 31 33 PM" src="https://github.com/user-attachments/assets/2a1ae97a-8da3-4908-867d-23967fbcdc3c">

2024-08-08 19:56 UTC, edlu77 commented
@LibbyUX What's the difference in behavior between the focus visible state and keyboard tab focus state? Seems like they mean the same thing...

2024-08-08 20:03 UTC, LibbyUX commented
@edlu77, @axdanbol helped me understand the differences between focus and focus visible:
- https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#focus_vs_focus-visible
- https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#comparing_focus_and_focus-visible

I was naming components "focus" in Figma, when in reality, it was focus visible functionality I was trying to achieve. I am working to update all component naming conventions to focus visible when needed, along with specifying new (and actual) focus states for components that could use it.

2024-08-08 20:13 UTC, edlu77 commented
@LibbyUX All right I see. Are we not using the red outline variant then?

2024-08-08 20:26 UTC, LibbyUX commented
@edlu77 for the sort header button, we will build both focus and focus-visible, please. 

Moving forward I will make sure the components I send to the Storybook design system use the proper naming convention for the CSS functionality they are trying to achieve. We will always have focus-visible for most buttons, but we may have focus states too, depending on how Angular is doing it.

I greatly appreciate your work on this one! We will soon be using this component a lot! 

<img width="967" alt="Screenshot 2024-08-08 at 4 26 22 PM" src="https://github.com/user-attachments/assets/1592ec96-7913-4b0b-a327-4a6c5d4769c4">

2024-08-20 18:53 UTC, axdanbol requested changes

2024-08-20 18:53 UTC, axdanbol commented on libs/design-system/table/src/lib/table.component.ts
Rename this to `table-demo.component.ts` and move into a table-demo directory

2024-08-20 18:53 UTC, axdanbol commented on libs/design-system/table/src/lib/table.component.html
> +  [dataSource]="dataSource || null"
Why `|| null`?

2024-08-20 18:53 UTC, axdanbol commented on libs/design-system/table/src/lib/table.component.ts
> +export class TableComponent implements AfterViewInit {
Rename to `TableDemoComponent`

2024-08-20 18:53 UTC, axdanbol commented on libs/design-system/table/src/lib/table.component.ts
> +  [name: string]: string | number;
No need for this to be generic in a demo component. Add `name` and `value` properties

2024-08-20 18:53 UTC, axdanbol commented on libs/design-system/table/src/lib/table.component.ts
> +  @ViewChild(MatSort) sort!: MatSort;
Use `viewChild.required(...)` instead of decorator

2024-08-20 18:53 UTC, axdanbol commented on libs/design-system/table/src/lib/table.component.ts
Also follow this example to simplify the component: https://material.angular.io/components/sort/overview#using-sort-with-the-mat-table

2024-08-20 18:53 UTC, axdanbol commented on libs/design-system/table/src/lib/table.component.ts
> +    this.dataSource.sort = this.sort;
Use an `effect` to set this in the constructor:
```ts
constructor() {
  effect(() => {
    this.dataSource.sort = this.sort();
  });
}
```

2024-08-20 18:53 UTC, axdanbol commented on libs/design-system/table/src/lib/table.component.ts
> +  data = input<TableData[]>([]);
Use `readonly` for properties that do not change

2024-08-20 18:53 UTC, axdanbol commented on libs/design-system/table/src/lib/table-styles/table-styles.component.scss
Update px to rem

2024-08-21 18:06 UTC, axdanbol commented on libs/design-system/table/src/lib/table-demo/table-demo.component.ts
> +  columns: string[] = [];
Just set the columns to `['name', 'value']`

2024-08-21 18:20 UTC, axdanbol commented on libs/design-system/table/src/lib/table-demo/table-demo.component.ts
> +  sortedData = this.data();
Remove

2024-08-21 18:20 UTC, axdanbol commented on libs/design-system/table/src/lib/table-demo/table-demo.component.ts
> +  sort = viewChild.required(MatSort);
readonly

2024-08-21 18:20 UTC, axdanbol commented on libs/design-system/table/src/lib/table-demo/table-demo.component.ts
> +  columns: string[] = [];
Also readonly

2024-08-21 18:21 UTC, axdanbol commented on libs/design-system/table/src/lib/table-demo/table-demo.component.ts
> +  dataSource = new MatTableDataSource(this.data());
Readonly

2024-08-21 18:21 UTC, axdanbol commented on libs/design-system/table/src/lib/table-demo/table-demo.component.ts
> +  ngAfterViewInit() {
Remove

2024-08-21 18:21 UTC, axdanbol commented on libs/design-system/table/src/lib/table-demo/table-demo.component.ts
> +  dataSource = new MatTableDataSource(this.data());
Initialize with the empty array `[]`

2024-08-21 18:22 UTC, axdanbol commented on libs/design-system/table/src/lib/table-demo/table-demo.component.ts
> +    });
Add effect to bind data:
```ts
effect(() => {
  this.dataSource.data = this.data();
});
```

2024-08-21 18:32 UTC, axdanbol commented on libs/design-system/table/src/lib/table-demo/table-demo.component.html
> +  @for (column of columns; track column) {
Just create one column def for `name` and `value` respectively instead of a for loop

2024-08-23 14:47 UTC, axdanbol approved these changes

2024-08-23 14:48 UTC, merged