add nav header to storybook
hubmapconsortium/hra-ui pull request #621
Opened 2024-08-08 17:28 UTC by bhushankhope

2024-08-12 17:59 UTC, LibbyUX submitted a review, later dismissed
@bhushankhope - Thanks for getting this started! I know we just touched base in person, but following up on here for us and our colleagues:

- We will get the navbar color closer to spec
- We will add our apps icon button (#573) for the sidenav entry point (#557)

It's looking great so far, thanks for all of your help on this!

2024-08-13 21:12 UTC, axdanbol requested changes
I don't see the ng-package.json file or changes in tsconfig.base.json that marks this as a secondary entrypoint?

2024-08-13 21:12 UTC, axdanbol commented on libs/design-system/nav-header/src/lib/nav-header.component.ts
> +import { AppLogosComponent, AppLogosVariant } from '../../../logos/apps/src/index';
Need to update the location and tsconfig.base.json of app logos so it can be imported from `@hra-ui/design-system/app-logos` instead

2024-08-13 21:12 UTC, axdanbol commented on libs/design-system/nav-header/src/lib/nav-header.component.ts
> +  variant = input<AppLogosVariant>();
Add `'default'` as a default value to this input

2024-08-13 21:12 UTC, axdanbol commented on libs/design-system/nav-header/src/lib/nav-header.component.html
> +  [variant]="variant() ?? 'default'"
Add the default in the component's input instead

2024-08-13 21:12 UTC, axdanbol commented on libs/design-system/nav-header/src/lib/nav-header.component.html
> +<button mat-icon-button hraIconButtonSize="large">
Should the icon size be affected by the variant?

2024-08-13 21:12 UTC, axdanbol commented on libs/design-system/nav-header/src/lib/nav-header.component.scss
> +  background-color: #eff2f5;
Colors should come from `sys-*` css variables

2024-08-13 21:12 UTC, axdanbol commented on libs/design-system/nav-header/src/lib/nav-header.component.scss
> +  justify-content: space-between;
Prefer using a filler div element over space-between

2024-08-14 15:43 UTC, axdanbol approved these changes

2024-08-14 21:50 UTC, merged