Design system storybook menu
hubmapconsortium/hra-ui pull request #650
Opened 2024-08-16 00:35 UTC by edlu77

#646, #645

2024-08-16 13:16 UTC, LibbyUX reviewed
This is perfect, thank you @edlu77 ! Do we have the medium and small variants as well? I can't find them currently, however, this large variant looks/feels perfect!

2024-08-19 14:45 UTC, LibbyUX approved these changes
Thank you so much @edlu77 ! Happy Monday!

2024-08-21 19:27 UTC, axdanbol requested changes
Please refactor this story in the same way as table, etc.

2024-08-27 16:07 UTC, axdanbol approved these changes

2024-08-27 17:02 UTC, merged