Add social media button stories
hubmapconsortium/hra-ui pull request #657
Opened 2024-08-20 14:47 UTC by edlu77

#654

2024-08-20 14:54 UTC, LibbyUX approved these changes
Excellent! Thank you @edlu77!

2024-08-20 18:36 UTC, axdanbol requested changes
Let's create an actual component for this use case as a social media button is a link with an icon with it's own set of styles

2024-08-21 19:24 UTC, axdanbol requested changes

2024-08-21 19:24 UTC, axdanbol commented on libs/design-system/social-media-button/src/lib/social-media-button.component.ts
> +
Export a type `SocialMediaName = 'x' | 'facebook' | ...`

2024-08-21 19:24 UTC, axdanbol commented on libs/design-system/social-media-button/src/lib/social-media-button.component.ts
> +  name = input.required<string>();
Readonly and update type to `SocialMediaName` from string

2024-08-21 19:24 UTC, axdanbol commented on libs/design-system/social-media-button/src/lib/social-media-button.component.ts
> +
Export a type `SocialMediaButtonSize = 'small' | 'large'`

2024-08-21 19:24 UTC, axdanbol commented on libs/design-system/social-media-button/src/lib/social-media-button.component.ts
> +  isSmall = input.required<boolean>();
Readonly, rename to size, and change the type to `SocialMediaButtonSize`

2024-08-21 19:24 UTC, axdanbol commented on libs/design-system/social-media-button/src/lib/social-media-button.component.ts
> +}
Add computed properties:
```ts
protected icon = computed(() => `social:${this.name()}${this.size() === 'large' ? '_large' : ''}`);
protected link = computed(() => SOCIAL_LINKS[this.name()]);
```

2024-08-21 19:24 UTC, axdanbol commented on libs/design-system/social-media-button/src/lib/social-media-button.component.html
> +<a [href]="links[name()]" target="_blank" rel="noopener noreferrer">
Use computed properties instead of complicated computations in the html template

2024-08-21 19:24 UTC, axdanbol commented on libs/design-system/social-media-button/src/lib/social-media-button.component.ts
> +  readonly links = SOCIAL_LINKS;
Remove (not needed when using computed properties)

2024-08-23 15:57 UTC, axdanbol approved these changes

2024-08-23 15:59 UTC, merged