create design system button stories
hubmapconsortium/hra-ui pull request #658
Opened 2024-08-20 19:17 UTC by bhushankhope

2024-08-22 18:16 UTC, LibbyUX reviewed
Hi, Bhushan! This looks great and it's almost ready. 

My only question:
- Is it possible to see the selected state for the nav cat button? It will need to hold the red underline in the selected state.

Thanks so much for everything!

![image](https://github.com/user-attachments/assets/343b04f6-087d-404b-b4fc-bda285660866)

2024-08-22 18:32 UTC, bhushankhope commented
@LibbyUX Check now. Added underline on selected state. [Link](https://github.com/hubmapconsortium/hra-ui/pull/658#issuecomment-2299597337)

2024-08-22 18:35 UTC, LibbyUX approved these changes
Thanks so much @bhushankhope!

2024-08-22 19:45 UTC, axdanbol requested changes
A couple of small tweaks

2024-08-22 19:45 UTC, axdanbol commented on libs/design-system/button/src/lib/button.component.stories.ts
Please change all `<a>` tags to `<button>`. It is quite frustrating that it opens a new page every time you click a button. (Remove href and target attributes as well)

2024-08-22 19:45 UTC, axdanbol commented on libs/design-system/button/src/lib/button-size/button-size.directive.ts
> +interface ButtonSizeAndFont {
Rename to `ButtonConfig`

2024-08-22 19:45 UTC, axdanbol commented on libs/design-system/button/src/lib/button-size/button-size.directive.ts
> +const BUTTON_SIZES: Record<string, ButtonSizeAndFont> = {
Rename to `BUTTON_CONFIG` and update type to `Record<ButtonSize, ButtonConfig>`

2024-08-23 15:56 UTC, axdanbol approved these changes

2024-08-23 15:57 UTC, merged