Add tree stories
hubmapconsortium/hra-ui pull request #664
Opened 2024-08-21 17:57 UTC by edlu77

2024-08-22 18:27 UTC, LibbyUX reviewed
Hi Edward, this is looking great. Thanks for getting this so close!

One question:
- Is it possible to situate the collapsed parent icon in the specified state?

Thanks so much!

![image](https://github.com/user-attachments/assets/7a0abeee-3128-4544-aa6f-6365cb1d370c)

2024-08-22 20:50 UTC, edlu77 commented
@LibbyUX I've changed the icon, it should be using the correct one now.

Question about keyboard navigation, do we still want the same behavior as in the FTU Explorer?

2024-08-24 03:32 UTC, LibbyUX commented
Hi @edlu77, yes please to the same keyboard tab functionality with the focus visible state.

Thanks so much for knocking this out!

2024-08-26 15:22 UTC, edlu77 commented
@LibbyUX Made some updates and the keyboard navigation should be working now. Let me know if there are any other changes needed!

2024-08-27 14:09 UTC, LibbyUX reviewed
Good morning, @edlu77! Thanks for the work on this! The tab looks good.

I just noticed there is a blue outline after pressing, probably because of the specified focus state variant. 

Is it possible to distinguish focus vs focus visible on this component? If not, let's just remove the focus state and go with focus visible only. I will delete the focus variant from our Figma library, too. 

I designed this component thinking we would be able to have separate looks for focus and focus visible, after a conversation with @axdanbol. No worries if it isn't possible, just let me know! Thanks so much and happy Tuesday! 

![72E1AD89-0DA3-44BF-9D88-1E345CE19688](https://github.com/user-attachments/assets/3886c9ad-1a07-48c2-9431-3c4953a0a41f)

2024-08-27 15:58 UTC, axdanbol requested changes
A few small tweaks

2024-08-27 15:58 UTC, axdanbol commented on libs/design-system/tree/src/lib/tree-styles/tree-styles.component.scss
> +  --mat-tree-node-text-font: 'Metropolis';
The font values should come from variables. Set the value to `var(--sys-label-medium-font)` and `var(--sys-label-medium-weight)` for the weight

2024-08-27 15:58 UTC, axdanbol commented on libs/design-system/tree/src/lib/tree-styles/tree-styles.component.scss
> +  --mat-tree-container-background-color: white;
Use `var(--sys-primary-container)`

2024-08-27 15:58 UTC, axdanbol commented on libs/design-system/tree/src/index.ts
> +export * from './lib/tree.component';
Don't export the demo component

2024-08-27 15:58 UTC, axdanbol commented on libs/design-system/tree/src/lib/tree.component.ts
Please rename this file and component to `TreeDemoComponent` (and the html file)

2024-08-27 15:58 UTC, axdanbol commented on libs/design-system/tree/src/lib/tree-size/tree-size.directive.ts
> +    '[style.--node-margin.rem]': '0.5',
Please move constants to the tree-styles scss file

2024-08-28 16:24 UTC, edlu77 commented
@LibbyUX Yes, that is the focus state. I agree it's a bit redundant since we already have a selected state which usually overrides it. You can only see this on expandable nodes that are clicked (since they can't be selected). I can remove the outline to make it cleaner.

2024-08-28 21:30 UTC, axdanbol approved these changes

2024-08-28 21:30 UTC, merged