Design system button toggle
hubmapconsortium/hra-ui pull request #671
Opened 2024-08-23 15:29 UTC by bhushankhope

2024-08-26 21:32 UTC, LibbyUX submitted a review, later dismissed
Perfect, thank you so much @bhushankhope !

2024-08-27 17:06 UTC, axdanbol requested changes
Story update

2024-08-27 17:06 UTC, axdanbol commented on libs/design-system/button-toggle/src/lib/button-toggle.component.stories.ts
> +export const SingleSelect: Story = {
Please separate single and multi select into two stories

2024-08-28 21:31 UTC, axdanbol approved these changes

2024-08-28 21:32 UTC, merged