Design system form field input
hubmapconsortium/hra-ui pull request #674
Opened 2024-08-26 18:49 UTC by bhushankhope

2024-08-26 21:28 UTC, LibbyUX submitted a review, later dismissed
Excellent! Thank you @bhushankhope !

2024-08-27 17:30 UTC, axdanbol requested changes

2024-08-27 17:30 UTC, axdanbol commented on libs/design-system/input/src/index.ts
> +export * from './lib/input-styles/input-styles.component';
No need to export this component

2024-08-27 17:30 UTC, axdanbol commented on libs/design-system/input/src/lib/input-styles/input-styles.component.scss
> +  font-family: 'Metropolis';
Read from a --sys variable. Add `-font` to get just the font family from the variables, i.e. `--sys-label-small-font`

2024-08-27 17:30 UTC, axdanbol commented on libs/design-system/input/src/lib/input.component.stories.ts
> +    template: `
Please split into 4 different stories

2024-08-28 21:33 UTC, axdanbol submitted a review, later dismissed

2024-08-29 14:47 UTC, merged