Refactor design system btns
hubmapconsortium/hra-ui pull request #698
Opened 2024-09-06 16:02 UTC by bhushankhope

2024-09-11 17:51 UTC, axdanbol requested changes
Missing letter-spacing. Please ensure every font declaration has corresponding letter-spacing

2024-09-11 17:51 UTC, axdanbol commented on libs/design-system/button/src/lib/button-styles/button-styles.component.scss
> +    font: var(--sys-label-large);
Please also set letter-spacing whenever you set font, i.e. `letter-spacing: var(--sys-label-large-tracking);`

2024-09-11 17:57 UTC, bhushankhope commented
@axdanbol Libby has recently updated some styles of the buttons to match material 3 designs. I will also update these styles and then re request the review.

2024-09-12 19:50 UTC, LibbyUX approved these changes
Thank you so much @bhushankhope ! They look excellent!

2024-09-19 21:44 UTC, axdanbol approved these changes

2024-09-19 21:44 UTC, merged