Add step indicator stories
hubmapconsortium/hra-ui pull request #704
Opened 2024-09-10 19:35 UTC by edlu77

#700

2024-09-10 19:46 UTC, LibbyUX submitted a review, later dismissed
Lovely, thank you @edlu77 !

2024-09-11 17:59 UTC, axdanbol requested changes
Please create a new component for the step indicator. We don't want to have to copy the styles all over the place. It will also make it easier to tweak the layout

2024-09-16 15:47 UTC, LibbyUX approved these changes
Thanks so much, @edlu77 !

2024-09-20 18:48 UTC, axdanbol approved these changes

2024-09-20 18:48 UTC, merged