Cde create vis app mvp2
hubmapconsortium/hra-ui pull request #735
Opened 2024-09-25 06:17 UTC by edlu77

#579

Various updates to CDE create vis page

2024-09-27 17:35 UTC, axdanbol requested changes
Use css variables and components from the design system

2024-09-27 17:35 UTC, axdanbol commented on apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.html
>        <span class="step-number">1</span>
Use new step indicator component from design-system

2024-09-27 17:35 UTC, axdanbol commented on apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.theme.scss
>  $gray-palette: map.get(palettes.$palettes, 'gray');
Move all the logic here into the regular scss file and use css variables instead

2024-10-02 16:32 UTC, edlu77 commented
@LibbyUX Our design system has been implemented for the create vis page, please review and let me know if there are any changes needed!

2024-10-04 14:09 UTC, LibbyUX approved these changes
Amazing, thank you so much @edlu77!

I have more work to do on our text field inputs after playing with this preview, but that's a separate issue for the design system. I will expand text fields to have helper text for error states, absolute positioned below the input field.

Thank you for knocking this out, it looks great. Happy Friday!

2024-10-15 18:11 UTC, axdanbol approved these changes

2024-10-15 18:11 UTC, merged