Add unified letter casing for headers; add headers to edge csv file downloads
hubmapconsortium/hra-ui pull request #742
Opened 2024-09-27 19:08 UTC by edlu77

#647

2024-10-02 19:29 UTC, axdanbol commented
I'm holding off on reviewing this while Bruce and I consider the exact column names. There are some conflicting comments in different issues that we need to figure out first

2024-10-04 14:20 UTC, LibbyUX commented
I followed up on my email to confirm the column headers/order of Edges/Cell Links downloads. Thanks! 

### Resources
- #647 
- Initial issue that morphed into a different feature request: #579

2024-10-04 20:12 UTC, LibbyUX commented
@axdanbol, @bherr2 - per @J-Yash and for tracking here:

> The column names/order Cell ID, X1, Y1, Z1, X2, Y2, Z2 is finalized. 

![image](https://github.com/user-attachments/assets/1b042d83-d554-45a1-83a6-0b64851dd2c7)

2024-10-15 18:13 UTC, axdanbol requested changes

2024-10-15 18:13 UTC, axdanbol commented on libs/cde-visualization/src/lib/cde-visualization/cde-visualization.component.ts
> +import { startCase } from 'lodash';
No need for lodash

2024-10-15 18:13 UTC, axdanbol commented on libs/cde-visualization/src/lib/cde-visualization/cde-visualization.component.ts
> +      const capsEntries = entries.map((entry) => [startCase(entry[0][0]) + entry[0].slice(1), entry[1]]);
Use `toUpperCase()` instead of startCase

2024-10-15 18:13 UTC, axdanbol commented on libs/cde-visualization/src/lib/cde-visualization/cde-visualization.component.ts
> +    return edges.map((item) => ({
The property names should be `Cell ID, X1, Y1, Z1, X2, Y2, Z2`

2024-10-17 15:05 UTC, axdanbol approved these changes

2024-10-17 15:05 UTC, merged