Ftu interactive svg
hubmapconsortium/hra-ui pull request #79
Opened 2023-02-20 15:49 UTC by edlu77

#50

2023-02-21 00:26 UTC, bherr2 commented
Do not commit SVGs, load them via URL (for now from ccf-releases GitHub pages). If it looks like SVGs will need to be modified extensively we can temporarily add them until it can be officially published in the HRA.

2023-03-07 21:50 UTC, axdanbol requested changes
A few tweaks

2023-03-07 21:50 UTC, axdanbol commented on libs/components/molecules/src/lib/interactive-svg/interactive-svg.component.ts
> +  @Input() svgNodeData: SvgNodeData[] = svgDataSet;
No longer used so it can be removed along with the svg-models.ts file

2023-03-07 21:50 UTC, axdanbol commented on libs/components/molecules/src/lib/interactive-svg/svg-models.ts
> +import { parse } from 'papaparse';
Entire file can be removed

2023-03-07 21:50 UTC, axdanbol commented on libs/components/molecules/src/lib/interactive-svg/interactive-svg.component.scss
> +  box-shadow: 1px 2px 1rem 2px rgba(0, 0, 0, 0.16);
px to rem

2023-03-07 21:50 UTC, axdanbol commented on libs/components/molecules/src/lib/interactive-svg/interactive-svg.stories.ts
> +  component: InteractiveSvgComponent,
Add after `component: InteractiveSvgComponent,` to improve storybook usage
```ts
argTypes: {
  control: 'select',
  options: [
    'assets/2d-ftu-large-intestine-crypt-lieberkuhn.svg',
    // Urls to the other svgs in assets
  ],
  defaultValue: 'assets/2d-ftu-large-intestine-crypt-lieberkuhn.svg'
}
```

2023-03-08 21:16 UTC, merged